#define STB_PERLIN_IMPLEMENTATION
#include <stb_perlin.h>
#include "perlin_gen.hpp"

#include <vector>
#include <random>
#include <glm/mat4x4.hpp>
#include <glm/glm.hpp>

/*
Process

This algorithm will iterate through all the blocks in a chunk, depending on
the perlin noise generation function, it will determine whether it is a solid
block or an air block.

The chunk data structure stores all the IDs of the blocks within the chunk,
the algorithm iterates through the chunk data and appends the vertex mesh data
based on the block ID to the std::vector v which is then uploaded to the buffer.

Optimizations
A 1D vector hash is used to optimize storage and lookup.
*/

/**
 * Define size constraints for a default chunk here
 * A 16x16x32 chunk is used as a default
 */
const unsigned int CHUNK_WIDTH = 16;
const unsigned int CHUNK_LENGTH = 16;
const unsigned int CHUNK_HEIGHT = 32;

// change these values to configure the generation
constexpr float airThreshold = 0.0f;

// implement block IDs for different types of blocks
const int airID = 0;
const int solidID = 1;

// textures IDs for different faces
const float defaultTex = 0;
const float sideTex = 1;
const float topTex = 2;
const float flowerTex = 3;

// chance of flower tile generating
constexpr float chance = 0.06f;

/**
 * @param v The array of vectors storing the data for the vertices which are generated by perlinGen
 * @param x Base x coordinate for the face
 * @param y Base y coordinate for the face
 * @param z Base z coordinate for the face
 * @param ID Id type for the block
 */
void PerlinGen::addTopFace(std::vector<Vertex>& v, int x, int z, int y, float ID) {
    glm::vec3 normal = glm::vec3(0, 1, 0);

    static std::mt19937 gen(std::random_device{}()); // only gets called once static
    static std::uniform_int_distribution<int> dist(0, 3); // 0,1,2,3
    
    int r = ID == 3 ? dist(gen) : 0;

    glm::vec2 uv[4] = {
        {0.0f, 0.0f}, // bottom-left
        {1.0f, 0.0f}, // bottom-right
        {1.0f, 1.0f}, // top-right
        {0.0f, 1.0f}  // top-left
    };

    glm::vec2 rotatedUV[4];

    for (int i = 0; i < 4; ++i) {
        switch(r) {
            case 0: rotatedUV[i] = uv[i]; break; // 0
            case 1: rotatedUV[i] = glm::vec2(1.0f - uv[i].y, uv[i].x); break; // 90
            case 2: rotatedUV[i] = glm::vec2(1.0f - uv[i].x, 1.0f - uv[i].y); break; // 180
            case 3: rotatedUV[i] = glm::vec2(uv[i].y, 1.0f - uv[i].x); break; // 270
        }
    }

    // triangle 1
    v.push_back({glm::vec3(x, y + 1, z), normal, rotatedUV[0], ID});
    v.push_back({glm::vec3(x + 1, y + 1, z), normal, rotatedUV[1], ID});
    v.push_back({glm::vec3(x + 1, y + 1, z + 1), normal, rotatedUV[2], ID});

    // triangle 2
    v.push_back({glm::vec3(x, y + 1, z), normal, rotatedUV[0], ID});
    v.push_back({glm::vec3(x + 1, y + 1, z + 1), normal, rotatedUV[2], ID});
    v.push_back({glm::vec3(x, y + 1, z + 1), normal, rotatedUV[3], ID});
}

// represents the -Y face (groundward)
void PerlinGen::addBottomFace(std::vector<Vertex>& v, int x, int z, int y, float ID) {
    glm::vec3 normal = glm::vec3(0, -1, 0);
    
    // triangle 1
    v.push_back({glm::vec3(x, y, z), normal, {0.0f, 0.0f}, ID});
    v.push_back({glm::vec3(x, y, z + 1), normal, {1.0f, 0.0f}, ID});
    v.push_back({glm::vec3(x + 1, y, z + 1), normal, {1.0f, 1.0f}, ID});

    // triangle 2
    v.push_back({glm::vec3(x, y, z), normal, {0.0f, 0.0f}, ID});
    v.push_back({glm::vec3(x + 1, y, z + 1), normal, {1.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x + 1, y, z), normal, {0.0f, 1.0f}, ID});
}

void PerlinGen::addRightFace(std::vector<Vertex>& v, int x, int z, int y, float ID) {
    glm::vec3 normal = glm::vec3(1, 0, 0);
    
    // triangle 1
    v.push_back({glm::vec3(x + 1, y, z), normal, {0.0f, 1.0f}, ID}); // bot left
    v.push_back({glm::vec3(x + 1, y + 1, z), normal, {0.0f, 0.0f}, ID}); // top left
    v.push_back({glm::vec3(x + 1, y + 1, z + 1), normal, {1.0f, 0.0f}, ID}); // top right

    // triangle 2
    v.push_back({glm::vec3(x + 1, y, z), normal, {0.0f, 1.0f}, ID}); // bot left
    v.push_back({glm::vec3(x + 1, y + 1, z + 1), normal, {1.0f, 0.0f}, ID}); // top right
    v.push_back({glm::vec3(x + 1, y, z + 1), normal, {1.0f, 1.0f}, ID}); // bot right
}

void PerlinGen::addLeftFace(std::vector<Vertex>& v, int x, int z, int y, float ID) {
    glm::vec3 normal = glm::vec3(-1, 0, 0);
    
    // triangle 1
    v.push_back({glm::vec3(x, y, z), normal, {1.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x, y, z + 1), normal, {0.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x, y + 1, z + 1), normal, {0.0f, 0.0f}, ID});

    // triangle 2
    v.push_back({glm::vec3(x, y, z), normal, {1.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x, y + 1, z + 1), normal, {0.0f, 0.0f}, ID});
    v.push_back({glm::vec3(x, y + 1, z), normal, {1.0f, 0.0f}, ID});
}

void PerlinGen::addFrontFace(std::vector<Vertex>& v, int x, int z, int y, float ID) {
    glm::vec3 normal = glm::vec3(0, 0, 1);
    
    // triangle 1
    v.push_back({glm::vec3(x, y, z + 1), normal, {0.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x, y + 1, z + 1), normal, {0.0f, 0.0f}, ID});
    v.push_back({glm::vec3(x + 1, y + 1, z + 1), normal, {1.0f, 0.0f}, ID});

    // triangle 2
    v.push_back({glm::vec3(x, y, z + 1), normal, {0.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x + 1, y + 1, z + 1), normal, {1.0f, 0.0f}, ID});
    v.push_back({glm::vec3(x + 1, y, z + 1), normal, {1.0f, 1.0f}, ID});
}

void PerlinGen::addBackFace(std::vector<Vertex>& v, int x, int z, int y, float ID) {
    glm::vec3 normal = glm::vec3(0, 0, -1);
    
    // triangle 1
    v.push_back({glm::vec3(x, y, z), normal, {1.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x + 1, y, z), normal, {0.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x + 1, y + 1, z), normal, {0.0f, 0.0f}, ID});

    // triangle 2
    v.push_back({glm::vec3(x, y, z), normal, {1.0f, 1.0f}, ID});
    v.push_back({glm::vec3(x + 1, y + 1, z), normal, {0.0f, 0.0f}, ID});
    v.push_back({glm::vec3(x, y + 1, z), normal, {1.0f, 0.0f}, ID});
}

/**
 * @param scale The scale used for the perlin generation size.
 * @return A vector of vertices storing the generated chunk.
 */
std::vector<Vertex> PerlinGen::generate(float scale, int chunkX, int chunkZ) {
    // result output
    std::vector<Vertex>v;

    // initialize chunk
    // structure is [x][z][y] to keep y as the vertical axis
    std::vector<std::vector<std::vector<int>>>chunk( // TODO: change to flat array
        CHUNK_WIDTH, std::vector<std::vector<int>>(
            CHUNK_LENGTH, std::vector<int> (
                CHUNK_HEIGHT, 0
            )
        )
    );

    // Helper to safely check if a block is air, treating out of bounds as air
    auto isAir = [&](int x, int z, int y) -> bool {
        if (x < 0 || x >= CHUNK_WIDTH ||
            z < 0 || z >= CHUNK_LENGTH ||
            y < 0 || y >= CHUNK_HEIGHT) {
            return true;  // treat out of bounds as air, always render face
        }
        return chunk[x][z][y] == airID;
    };

    // random flower texture generator
    std::mt19937 gen(std::random_device{}());
    std::uniform_real_distribution<float> dist(0.0f, 1.0f);

    // TODO: remove edge of chunk faces
    for (int i = 0; i < CHUNK_WIDTH; i++) {
        for (int j = 0; j < CHUNK_LENGTH; j++) {
            for (int k = 0; k < CHUNK_HEIGHT; k++) {
                float nX = (static_cast<float>(i) + static_cast<float>(chunkX) * static_cast<float>(CHUNK_WIDTH)) * scale;
                float nZ = (static_cast<float>(j) + static_cast<float>(chunkZ) * static_cast<float>(CHUNK_LENGTH)) * scale;
                float nY = static_cast<float>(k) * scale;
                
                float noiseValue = stb_perlin_noise3(nX, nY, nZ, 0, 0, 0);

                // density calculation with height gradient
                float heightGradient = (static_cast<float>(k) / CHUNK_HEIGHT) * 2.0f - 1.0f;
                float finalValue = noiseValue - heightGradient;

                if (finalValue > airThreshold) {
                    chunk[i][j][k] = solidID;
                }
                else {
                    chunk[i][j][k] = airID;
                }
            }
        }
    }
    // TODO: fix face generation on chunk edges
    for (int i = 0; i < CHUNK_WIDTH; i++) {
        for (int j = 0; j < CHUNK_LENGTH; j++) {
            for (int k = 0; k < CHUNK_HEIGHT; k++) {
                int blockType = chunk[i][j][k];

                int worldX = i + chunkX * CHUNK_WIDTH;
                int worldZ = j + chunkZ * CHUNK_LENGTH;
                // int worldY = k;

                if (blockType == 0) continue;

                if (blockType == 1) {
                    if (isAir(i, j, k + 1)) {
                        float r = dist(gen);
                        addTopFace(v, worldX, worldZ, k, r < chance ? flowerTex : topTex);
                    }
                    // bottom
                    if (isAir(i, j, k - 1)) {
                        addBottomFace(v, worldX, worldZ, k, defaultTex);
                    }
                    // front (+z)
                    if (isAir(i, j + 1, k)) {
                        float tex = chunk[i][j][k + 1] == 0 ? sideTex : defaultTex;  // grass if exposed top
                        // but need bounds check for k+1 too:
                        bool topExposed = (k + 1 >= CHUNK_HEIGHT) || chunk[i][j][k + 1] == airID;
                        addFrontFace(v, worldX, worldZ, k, topExposed ? sideTex : defaultTex);
                    }
                    // back (-z)
                    if (isAir(i, j - 1, k)) {
                        bool topExposed = (k + 1 >= CHUNK_HEIGHT) || chunk[i][j][k + 1] == airID;
                        addBackFace(v, worldX, worldZ, k, topExposed ? sideTex : defaultTex);
                    }
                    // right (+x)
                    if (isAir(i + 1, j, k)) {
                        bool topExposed = (k + 1 >= CHUNK_HEIGHT) || chunk[i][j][k + 1] == airID;
                        addRightFace(v, worldX, worldZ, k, topExposed ? sideTex : defaultTex);
                    }
                    // left (-x)
                    if (isAir(i - 1, j, k)) {
                        bool topExposed = (k + 1 >= CHUNK_HEIGHT) || chunk[i][j][k + 1] == airID;
                        addLeftFace(v, worldX, worldZ, k, topExposed ? sideTex : defaultTex);
                    }
                }
            }
        }
    }
    
    return v;
};